# Generated by Django 5.2.6 on 2025-09-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutdoorWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(70)])),
                ('feels_like', models.FloatField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(70)])),
                ('temp_min', models.FloatField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(70)])),
                ('temp_max', models.FloatField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(70)])),
                ('humidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.IntegerField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1200)])),
                ('weather_main', models.CharField(max_length=255)),
                ('weather_description', models.CharField(max_length=255)),
                ('weather_icon', models.CharField(max_length=255)),
                ('visibility', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('wind_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('wind_deg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('clouds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
