# Generated by Django 5.0 on 2024-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
