# Generated by Django 5.2.5 on 2025-09-12 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_weather", "0002_alter_outdoorweatherdata_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outdoorweatherdata",
            options={
                "ordering": ["-created"],
                "verbose_name": "OpenWeather-Data",
                "verbose_name_plural": "OpenWeather-Data",
            },
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="clouds",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="feels_like",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(70),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="humidity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="pressure",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(500),
                    django.core.validators.MaxValueValidator(1200),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="temp_max",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(70),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="temp_min",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(70),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="temperature",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(70),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="visibility",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="wind_deg",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(360),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outdoorweatherdata",
            name="wind_speed",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ]
            ),
        ),
    ]
