# Generated by Django 5.2.5 on 2025-09-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_weather", "0003_alter_outdoorweatherdata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outdoorweatherdata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "OpenWeather-Data",
                "verbose_name_plural": "OpenWeather-Data",
            },
        ),
        migrations.RenameField(
            model_name="outdoorweatherdata",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="outdoorweatherdata",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
