# Generated by Django 5.2.5 on 2025-08-08 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi_sensor", "0002_alter_indoorsensordata_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indoorsensordata",
            options={
                "ordering": ["-created"],
                "verbose_name": "Innenraum-Sensordaten",
                "verbose_name_plural": "Innenraum-Sensordaten",
            },
        ),
        migrations.AlterField(
            model_name="indoorsensordata",
            name="co2",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="indoorsensordata",
            name="humidity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="indoorsensordata",
            name="pressure",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(1100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="indoorsensordata",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[
                    django.core.validators.MinValueValidator(-40),
                    django.core.validators.MaxValueValidator(85),
                ],
            ),
        ),
    ]
