# Generated by Django 5.2.5 on 2025-09-12 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi_sensor", "0003_alter_indoorsensordata_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indoorsensordata",
            name="co2",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="indoorsensordata",
            name="humidity",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="indoorsensordata",
            name="pressure",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(1100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="indoorsensordata",
            name="temperature",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-40),
                    django.core.validators.MaxValueValidator(85),
                ]
            ),
        ),
    ]
