# Generated by Django 5.2.5 on 2025-09-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi_sensor", "0004_alter_indoorsensordata_co2_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indoorsensordata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Innenraum-Sensordaten",
                "verbose_name_plural": "Innenraum-Sensordaten",
            },
        ),
        migrations.RenameField(
            model_name="indoorsensordata",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="indoorsensordata",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
