# Generated by Django 5.2.6 on 2025-10-24 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_station", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indoorsensordata",
            name="co2",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
    ]
