# Generated by Neluxx - 5.2.6 on 2025-10-29 14:24

from django.db import migrations


def subtract_three_from_temperature(apps, schema_editor) -> None:
    """Subtract 3 degrees from all temperature readings in IndoorSensorData"""
    IndoorSensorData = apps.get_model('weather_station', 'IndoorSensorData')

    # Update all records, subtract 3 from the temperature field
    for record in IndoorSensorData.objects.all():
        if record.temperature is not None:
            record.temperature -= 3
            record.save(update_fields=['temperature'])


def reverse_temperature_change(apps, schema_editor) -> None:
    """Reverse migration: add 3 degrees to all temperature readings"""
    IndoorSensorData = apps.get_model('weather_station', 'IndoorSensorData')

    # Update all records, adding 3 to the temperature field
    for record in IndoorSensorData.objects.all():
        if record.temperature is not None:
            record.temperature += 3
            record.save(update_fields=['temperature'])


class Migration(migrations.Migration):

    dependencies = [
        ("weather_station", "0002_alter_indoorsensordata_co2"),
    ]

    operations = [
        migrations.RunPython(
            subtract_three_from_temperature,
            reverse_code=reverse_temperature_change
        ),
    ]
