# Generated by Django 5.2.7 on 2025-12-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather_station", "0002_alter_indoorsensordata_co2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OutdoorWeatherData",
        ),
    ]
